EX2: ceasar_ext.h File Reference
ceasar_ext.h File Reference
All exposed functions and types to be used by someone who wants to call the Ceasar lib/program.
#include "common_types.h"
Functions
int main (int argc, char *argv[])
Encrypts or decrypts a message from a file.
Detailed Description
All exposed functions and types to be used by someone who wants to call the Ceasar lib/program.
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file ceasar_ext.h.
Function Documentation
main()
int main (int argc, char * argv[])
Encrypts or decrypts a message from a file.
Parameters
[in] argc
[in] argv On top of the function name the program takes a maximum of three more arguments. These parameters must appear in the following order:
input file name string: holdes the full/relative path for the text file to be cyphered.
encryption key: the key the program will use to encrypt or decrypt the file.
number of threads: the number of threads to use to encrypt or decrypt the file.
encrypt/decrypt flag: indication weather to encrypt or decrypt the file, the option are '-e' and '-d'
Returns
int On success the return value is 0 (ERROR_OK), a nonzero vlaue will be returned on failure, indicating the failure.
Definition at line 33 of file ceasar.c.
 {
     // Debug Prefix
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK; // Assume program runs correctly, update status as we go.
     HANDLE* p_thread_handles = NULL; // Allocate handles to all threads
     HANDLE input_file_handle = NULL;
     HANDLE output_file_handle = NULL; // handle to output file
     ceasar_args_t s_ceasar_params;
     // create a do{}while(0) loop, to enable breaking out of loop for error handling and cleanup.
     do
     {
         /*------------------------------
          * Step 1: Command line parsing
          * ---------------------------*/
         e_status = parse_command_line_input(argc, argv, &s_ceasar_params);
         CHECK_AND_BREAK(e_status);
         /*------------------------------
          * Step 2: Prepare for thread processing
          * ---------------------------*/
         // Allocate memory for threads parameters and handles
         p_thread_handles = (HANDLE*)malloc(s_ceasar_params.num_of_threads * sizeof(HANDLE));
         if (NULL == p_thread_handles)
         {
             print_error_msg("Error when allocating memory\n");
             e_status = ERROR_FAILED_TO_ALLOCATE_MEMORY_E;
             break;
         }
         // Initialize pointers to thread (help with cleanup later)
         for(int thread_idx = 0; thread_idx < s_ceasar_params.num_of_threads; thread_idx++)
         {
             p_thread_handles[thread_idx] = NULL;
         }
         // We use calloc here to make sure the parameters are initialized at zero.
         encryption_thread_params_t *p_thread_params = (encryption_thread_params_t*)malloc(s_ceasar_params.num_of_threads * sizeof(encryption_thread_params_t));
         if (NULL == p_thread_params)
         {
             print_error_msg("Error when allocating memory\n");
             e_status = ERROR_FAILED_TO_ALLOCATE_MEMORY_E;
             break;
         }
         else
         {
             memset(p_thread_params, -1, s_ceasar_params.num_of_threads * sizeof(encryption_thread_params_t));
         }
         // Encrypt of decrypt mode: output filename, encryption sign key change.
         char *p_output_file_name = NULL;
         if(ENCRYPT_MODE_E == s_ceasar_params.e_encryption_flag)
         {
             p_output_file_name = "encrypted_file.txt";
             s_ceasar_params.encryption_key = -s_ceasar_params.encryption_key;
         }
         else if(DECRYPT_MODE_E == s_ceasar_params.e_encryption_flag)
         {
             p_output_file_name = "decrypted_file.txt";
         }
         else
         {
             e_status = ERROR_INVALID_PARAM_E;
             print_error_msg("Invalid encryption mode. Recieved value of %d\n", s_ceasar_params.e_encryption_flag);
         }
         CHECK_AND_BREAK(e_status);
         // Get start and end positions
         // Open input file and get the starting and end positions of the file.
         // Count number of lines in the file.
         // Open output file:
         input_file_handle = CreateFileA(
             s_ceasar_params.p_file_name,   // creates output file
             GENERIC_READ,
             FILE_SHARE_READ,
             NULL,
             OPEN_EXISTING,
             FILE_ATTRIBUTE_NORMAL,
             NULL
         );
         e_status = split_lines_between_threads(input_file_handle, s_ceasar_params.num_of_threads, p_thread_params);
         CHECK_AND_BREAK(e_status);
         CloseHandle(input_file_handle);
         // Open output file:
         const long end_pos = p_thread_params[s_ceasar_params.num_of_threads - 1].end_pos;
         output_file_handle = CreateFileA(
              p_output_file_name,   // creates output file
              GENERIC_WRITE,
              FILE_SHARE_WRITE, //SHARE
              NULL,
              CREATE_ALWAYS,            // create new doesnt create a file if it already exist
              FILE_ATTRIBUTE_NORMAL,
              NULL
         );
         if (output_file_handle == INVALID_HANDLE_VALUE)
         {
             print_error_msg("Creating a output file in a thread FAILED!\n");
             break;
         }
         else
         {
             BOOL set_file_pointer_status = SetFilePointer(
                 output_file_handle,
                 end_pos+1,
                 NULL,
                 FILE_BEGIN
             );
             BOOL set_end_of_file_status = SetEndOfFile(output_file_handle);
             if(! set_end_of_file_status)
             {
                 print_error_msg("Failed to set end of output file!\n");
             }
             CloseHandle(output_file_handle);
             output_file_handle = NULL;
         }
         /*------------------------------
          * Step 3: Thread Call
          * ---------------------------*/
         for(int thread_idx = 0; thread_idx < s_ceasar_params.num_of_threads; thread_idx++)
         {
             p_thread_params[thread_idx].p_input_file_name   = s_ceasar_params.p_file_name;
             p_thread_params[thread_idx].p_output_file_name  = p_output_file_name;
             p_thread_params[thread_idx].encryption_key      = s_ceasar_params.encryption_key;
             LPDWORD p_thread_id = NULL;
             p_thread_handles[thread_idx] = CreateThread(
                 NULL,                               /*  default security attributes */
                 0,                                  /*  use default stack size */
                 create_encryption_thread,           /*  thread function */
                 &p_thread_params[thread_idx],       /*  argument to thread function */
                 0,                                  /*  use default creation flags */
                 p_thread_id);                       /*  returns the thread identifier */
             if (NULL == p_thread_handles[thread_idx])
             {
                 print_error_msg("Error when creating thread\n");
                 e_status = ERROR_FAILED_TO_CREATE_THREAD_E;
                 break;
             }
         }
     }while(0);
     /*------------------------------
     * Step 4: Clean Up
     * ---------------------------*/
     DWORD wait_code = WaitForMultipleObjects(s_ceasar_params.num_of_threads, p_thread_handles, 1, INFINITE);
     if (WAIT_OBJECT_0 != wait_code)
     {
         print_error_msg("Error when waiting");
         return 1;
     }
     // Debug Suffix
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References CHECK_AND_BREAK, create_encryption_thread(), DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, DECRYPT_MODE_E, ceasar_args_s::e_encryption_flag, ENCRYPT_MODE_E, encryption_thread_params_s::encryption_key, ceasar_args_s::encryption_key, encryption_thread_params_s::end_pos, ERROR_FAILED_TO_ALLOCATE_MEMORY_E, ERROR_FAILED_TO_CREATE_THREAD_E, ERROR_INVALID_PARAM_E, ERROR_OK, ceasar_args_s::num_of_threads, ceasar_args_s::p_file_name, encryption_thread_params_s::p_input_file_name, encryption_thread_params_s::p_output_file_name, parse_command_line_input(), print_error_msg, and split_lines_between_threads().