EX2: ceasar.c File Reference
ceasar.c File Reference
#include "ceasar.h"
Functions
int main (int argc, char *argv[])
Encrypts or decrypts a message from a file.
static error_e main_thread_function (const char *p_input_file_name, const char *p_output_file_name, long long u_start_pos, long long u_end_pos, int encryption_key)
TODO: Vladimir - Fill detailed description of the function. This info should include both calling instructions and implemntation details.
Detailed Description
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file ceasar.c.
Function Documentation
main()
int main (int argc, char * argv[])
Encrypts or decrypts a message from a file.
Parameters
[in] argc
[in] argv On top of the function name the program takes a maximum of three more arguments. These parameters must appear in the following order:
input file name string: holdes the full/relative path for the text file to be cyphered.
encryption key: the key the program will use to encrypt or decrypt the file.
number of threads: the number of threads to use to encrypt or decrypt the file.
encrypt/decrypt flag: indication weather to encrypt or decrypt the file, the option are '-e' and '-d'
Returns
int On success the return value is 0 (ERROR_OK), a nonzero vlaue will be returned on failure, indicating the failure.
Definition at line 33 of file ceasar.c.
 {
     // Debug Prefix
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK; // Assume program runs correctly, update status as we go.
     // create a do{}while(0) loop, to enable breaking out of loop for error handling and cleanup.
     do
     {
         /*------------------------------
          * Step 1: Command line parsing
          * ---------------------------*/
         ceasar_args_t s_ceasar_params;
         e_status = parse_command_line_input(argc, argv, &s_ceasar_params);
         if(ERROR_OK != e_status)
         {
             break;
         }
         /*------------------------------
          * Step 2: Prepare for thread processing
          * ---------------------------*/
         char *p_output_file_name = NULL;
         if(ENCRYPT_MODE_E == s_ceasar_params.e_encryption_flag)
         {
             p_output_file_name = "encrypted_file.txt";
         }
         else if(DECRYPT_MODE_E == s_ceasar_params.e_encryption_flag)
         {
             p_output_file_name = "decrypted_file.txt";
             s_ceasar_params.encryption_key = -s_ceasar_params.encryption_key;
         }
         else
         {
             e_status = ERROR_INVALID_PARAM_E;
             print_error_msg("Invalid encryption mode. Recieved value of %d\n", s_ceasar_params.e_encryption_flag);
         }
         if(ERROR_OK != e_status)
         {
             break;
         }
         // TODO: Matan
         // Open input file and get the starting and end positions of the file.
         long long    u_start_pos = 0UL;
         long long    u_end_pos = 0UL;
         /*------------------------------
          * Step 3: Thread Call
          * ---------------------------*/
         e_status = main_thread_function(
             s_ceasar_params.p_file_name,      /* Input file name */
             p_output_file_name,               /* Output file name */
             u_start_pos,                      /* Starting position - Inclusive */
             u_end_pos,                        /* End position - Exclusive*/
             s_ceasar_params.encryption_key    /* Modified encryption key - reflects encryption mode*/
         );
     }while(0);
     /*------------------------------
     * Step 4: Clean Up
     * ---------------------------*/
     // TODO: Matan
     // Debug Suffix
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, DECRYPT_MODE_E, ceasar_args_s::e_encryption_flag, ENCRYPT_MODE_E, ceasar_args_s::encryption_key, ERROR_INVALID_PARAM_E, ERROR_OK, main_thread_function(), ceasar_args_s::p_file_name, parse_command_line_input(), and print_error_msg.
main_thread_function()
static error_e main_thread_function (const char * p_input_file_name, const char * p_output_file_name, long long u_start_pos, long long u_end_pos, int encryption_key) static
TODO: Vladimir - Fill detailed description of the function. This info should include both calling instructions and implemntation details.
Parameters
[in] p_input_file_name
[in] p_output_file_name
[in] u_start_pos
[in] u_end_pos
[in] encryption_key
Returns
error_e
Definition at line 126 of file ceasar.c.
 {
     // Debug Prefix
     DEBUG_PRINT_FUNCTION_START();
     error_e e_status = ERROR_OK; // Assume program runs correctly, update status as we go.
     // create a do{}while(0) loop, to enable breaking out of loop for error handling and cleanup.
     do
     {
         /*------------------------------
          * Step 1: Open Input File
          * ---------------------------*/
         // TODO: Vladimir
         /*------------------------------
          * Step 2: Open Output File
          * ---------------------------*/
         // TODO: Vladimir
         /*------------------------------
          * Step 3: Encrypt/Decrypt - loop from start to end
          * ---------------------------*/
         // TODO: Vladimir
     }while(0);
     /*------------------------------
     * Step 4: Clean Up
     * ---------------------------*/
    // TODO: Vladimir
    // * Make sure all files are closed.
    // * Deallocated any allocated memory
     // Debug Suffix
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, and ERROR_OK.
Referenced by main().