EX2: command_line_parsing.h File Reference
command_line_parsing.h File Reference
#include <ctype.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include "hardCodedData.h"
#include "common_types.h"
Macros
#define MIN_ALLOWED_ARGS (3)
Minimum allowed arguments. ProgramName InputFilePath EnctyptionKey.
#define ALLOWED_ARGS_WITH_THREADS_NUM (MIN_ALLOWED_ARGS + 1)
Minimum allowed arguments. ProgramName InputFilePath EnctyptionKey [ThreadsNum].
#define MAX_ALLOWED_ARGS (5)
Minimum allowed arguments. ProgramName InputFilePath EnctyptionKey [ThreadsNum] [-e| -d].
#define FILE_NAME_ARG_INDEX (1)
#define ENCRYPTION_KEY_ARG_INDEX (2)
#define THREAD_NUM_ARG_INDEX (3)
#define ENCRYPTION_FLAG_ARG_INDEX (4)
#define MIN_ALLOWED_ENCRYPTION_KEY (1)
#define MAX_ALLOWED_ENCRYPTION_KEY (26)
#define DEFUALT_THREAD_NUM (1)
#define MAX_THREAD_NUM (16)
#define DECRYPT_FLAG ("-d")
#define ENCRYPT_FLAG ("-e")
#define DECRYPT_FLAG_CAPS ("-D")
#define ENCRYPT_FLAG_CAPS ("-E")
#define DEFUALT_ENCRYPTION_FLAG (DECRYPT_MODE_E)
#define DEFUALT_ENCRYPTION_FLAG_STRING (DECRYPT_FLAG)
Functions
error_e parse_command_line_input (int argc_, char *argv_[], ceasar_args_t *p_output_args)
parsing the command line, validates input integrity and fills the arg structure. CAUTION: This function allocates memory which must be freed. The command line expected to be of the form: 0. program name.
static int parse_encryption_key (const char *p_encryption_key_string)
Extracts encryption key integer from string.
static int parse_num_of_threads (const char *p_num_of_threads_string)
converts string to int. Validates string has only numbers.
static encryption_mode_e parse_encryption_flag (const char *p_encryption_mode_string)
converts string to mode. Validates string is one of the allowed flags "-e" or "-d".
static int get_int_from_string (const char *p_string)
Get the int from string object extract digits character from string.
static void print_usage_msg (void)
print the command line usage for Ceasar program. Call when user entered wrong number of arguments or invalid values.
Detailed Description
Author
Matan Levy (levym.nosp@m.atan.nosp@m.levy@.nosp@m.gmai.nosp@m.l.com)
Version
0.1
Date
2020-11-09
Copyright
Copyright (c) 2020
Definition in file command_line_parsing.h.
Macro Definition Documentation
ALLOWED_ARGS_WITH_THREADS_NUM
#define ALLOWED_ARGS_WITH_THREADS_NUM (MIN_ALLOWED_ARGS + 1)
Minimum allowed arguments. ProgramName InputFilePath EnctyptionKey [ThreadsNum].
Definition at line 32 of file command_line_parsing.h.
DECRYPT_FLAG
#define DECRYPT_FLAG ("-d")
Definition at line 46 of file command_line_parsing.h.
DECRYPT_FLAG_CAPS
#define DECRYPT_FLAG_CAPS ("-D")
Definition at line 48 of file command_line_parsing.h.
DEFUALT_ENCRYPTION_FLAG
#define DEFUALT_ENCRYPTION_FLAG (DECRYPT_MODE_E)
Definition at line 50 of file command_line_parsing.h.
DEFUALT_ENCRYPTION_FLAG_STRING
#define DEFUALT_ENCRYPTION_FLAG_STRING (DECRYPT_FLAG)
Definition at line 51 of file command_line_parsing.h.
DEFUALT_THREAD_NUM
#define DEFUALT_THREAD_NUM (1)
Definition at line 43 of file command_line_parsing.h.
ENCRYPT_FLAG
#define ENCRYPT_FLAG ("-e")
Definition at line 47 of file command_line_parsing.h.
ENCRYPT_FLAG_CAPS
#define ENCRYPT_FLAG_CAPS ("-E")
Definition at line 49 of file command_line_parsing.h.
ENCRYPTION_FLAG_ARG_INDEX
#define ENCRYPTION_FLAG_ARG_INDEX (4)
Definition at line 38 of file command_line_parsing.h.
ENCRYPTION_KEY_ARG_INDEX
#define ENCRYPTION_KEY_ARG_INDEX (2)
Definition at line 36 of file command_line_parsing.h.
FILE_NAME_ARG_INDEX
#define FILE_NAME_ARG_INDEX (1)
Definition at line 35 of file command_line_parsing.h.
MAX_ALLOWED_ARGS
#define MAX_ALLOWED_ARGS (5)
Minimum allowed arguments. ProgramName InputFilePath EnctyptionKey [ThreadsNum] [-e| -d].
Definition at line 33 of file command_line_parsing.h.
MAX_ALLOWED_ENCRYPTION_KEY
#define MAX_ALLOWED_ENCRYPTION_KEY (26)
Definition at line 41 of file command_line_parsing.h.
MAX_THREAD_NUM
#define MAX_THREAD_NUM (16)
Definition at line 44 of file command_line_parsing.h.
MIN_ALLOWED_ARGS
#define MIN_ALLOWED_ARGS (3)
Minimum allowed arguments. ProgramName InputFilePath EnctyptionKey.
Definition at line 31 of file command_line_parsing.h.
MIN_ALLOWED_ENCRYPTION_KEY
#define MIN_ALLOWED_ENCRYPTION_KEY (1)
Definition at line 40 of file command_line_parsing.h.
THREAD_NUM_ARG_INDEX
#define THREAD_NUM_ARG_INDEX (3)
Definition at line 37 of file command_line_parsing.h.
Function Documentation
get_int_from_string()
static int get_int_from_string (const char * p_string) static
Get the int from string object extract digits character from string.
Parameters
[in] p_string
Returns
int return 0 will be invalid return value, thought the input string can potentionaly be 0. This value should be treated carefully by caller function.
parse_command_line_input()
error_e parse_command_line_input (int argc_, char * argv_[], ceasar_args_t * p_output_args)
parsing the command line, validates input integrity and fills the arg structure. CAUTION: This function allocates memory which must be freed. The command line expected to be of the form: 0. program name.
[MUST]input file name string: holdes the full/relative path for the text file to be cyphered. MUST
[MUST]encryption key: the key the program will use to encrypt or decrypt the file.
[OPT] number of threads: the number of threads to use to encrypt or decrypt the file. Default: 1
[OPT] encrypt/decrypt flag: indication weather to encrypt or decrypt the file, the option are '-e' and '-d'. Defualt: encrypt.
Parameters
[in] argc_
[in] argv_
[in] p_output_args
Returns
error_e 0 (ERROR_OK) on success, nonzero on failure.
[MUST]input file name string: holdes the full/relative path for the text file to be cyphered. MUST
[MUST]encryption key: the key the program will use to encrypt or decrypt the file.
[OPT] number of threads: the number of threads to use to encrypt or decrypt the file. Default: 1
[OPT] encrypt/decrypt flag: indication weather to encrypt or decrypt the file, the option are '-e' and '-d'. Defualt: encrypt. Implemntation: Stright forward, reading the input, and constantly checking for the validity fo the input. Pitfalls: converting the string to int, allocating memory for strings.
Parameters
[in] argc_
[in] argv_
[in] p_output_args
Returns
error_e 0 (ERROR_OK) on success, nonzero on failure.
Definition at line 42 of file command_line_parsing.c.
 {
     DEBUG_PRINT_FUNCTION_START();
     DEBUG_PRINT(DEBUG_LEVEL_TWO, "Input Arguments: <program_name>, <input_file_name>, <encryption_key>, <num_of_threads>, <encryption_flag>\n");
     for (int u_param_idx = 0; u_param_idx < argc_; u_param_idx++)
     {
         DEBUG_PRINT_ARG("%s\n", argv_[u_param_idx]);
     }
     error_e e_status = ERROR_OK;
     // Verify number of arguments.
     if ((argc_ < MIN_ALLOWED_ARGS) || (argc_ > MAX_ALLOWED_ARGS))
     {
         print_error_msg("Invalid number of arguments, given %d while expecting between %d to %d (inclusive)\n", argc_, MIN_ALLOWED_ARGS, MAX_ALLOWED_ARGS);
         e_status = ERROR_INVALID_NUMBER_OF_PARAMETERS_E;
     }
     else
     {
         /* Valid argc_ input */
         p_output_args->p_file_name        = argv_[FILE_NAME_ARG_INDEX];
         p_output_args->encryption_key     = parse_encryption_key(argv_[ENCRYPTION_KEY_ARG_INDEX]);
         // Set defualt values for optional params
         p_output_args->num_of_threads     = DEFUALT_THREAD_NUM;
         p_output_args->e_encryption_flag  = DEFUALT_ENCRYPTION_FLAG;
         switch (argc_)
         {
         case MIN_ALLOWED_ARGS:
             printf("Optional parameters, num_of_threads and decrypt/encrypt flag were not specified\n");
             printf("Setting default values:\n");
             printf("<num_of_threads> = %d\n", p_output_args->num_of_threads);
             printf("<e_encryption_flag> = %s\n", DEFUALT_ENCRYPTION_FLAG_STRING);
             break;
         case ALLOWED_ARGS_WITH_THREADS_NUM:
             printf("Optional parameter decrypt/encrypt flag was not specified\n");
             printf("Setting default value:\n");
             printf("<e_encryption_flag> = %s\n", DEFUALT_ENCRYPTION_FLAG_STRING);
             p_output_args->num_of_threads = parse_num_of_threads(argv_[THREAD_NUM_ARG_INDEX]);
             break;
         case MAX_ALLOWED_ARGS:
             p_output_args->num_of_threads = parse_num_of_threads(argv_[THREAD_NUM_ARG_INDEX]);
             p_output_args->e_encryption_flag = parse_encryption_flag(argv_[ENCRYPTION_FLAG_ARG_INDEX]);
             break;
         default:
             break;
         }
     }
     if(-1 == p_output_args->encryption_key)
     {
         print_error_msg("parse_command_line_input(): Failed to parse the encryption key.\n");
         e_status = ERROR_INVALID_ENCRYPTION_KEY_E;
     }
     if(-1 == p_output_args->num_of_threads)
     {
         print_error_msg("parse_command_line_input(): Failed to parse number of threads.\n");
         e_status = ERROR_INVALID_THREAD_NUM_E;
     }
     if(INVALID_ENCRYPTION_MODE_E == p_output_args->e_encryption_flag)
     {
         print_error_msg("parse_command_line_input(): Failed to parse the encryption flag.\n");
         e_status = ERROR_INVALID_ENCRYPTION_FLAG_E;
     }
     // Print useage instructions
     if(ERROR_OK != e_status)
     {
         print_usage_msg();
     }
     DEBUG_PRINT_FUNCTION_END();
     return e_status;
 }
References ALLOWED_ARGS_WITH_THREADS_NUM, DEBUG_LEVEL_TWO, DEBUG_PRINT, DEBUG_PRINT_ARG, DEBUG_PRINT_FUNCTION_END, DEBUG_PRINT_FUNCTION_START, DEFUALT_ENCRYPTION_FLAG, DEFUALT_ENCRYPTION_FLAG_STRING, DEFUALT_THREAD_NUM, ceasar_args_s::e_encryption_flag, ENCRYPTION_FLAG_ARG_INDEX, ceasar_args_s::encryption_key, ENCRYPTION_KEY_ARG_INDEX, ERROR_INVALID_ENCRYPTION_FLAG_E, ERROR_INVALID_ENCRYPTION_KEY_E, ERROR_INVALID_NUMBER_OF_PARAMETERS_E, ERROR_INVALID_THREAD_NUM_E, ERROR_OK, FILE_NAME_ARG_INDEX, INVALID_ENCRYPTION_MODE_E, MAX_ALLOWED_ARGS, MIN_ALLOWED_ARGS, ceasar_args_s::num_of_threads, ceasar_args_s::p_file_name, parse_encryption_flag(), parse_encryption_key(), parse_num_of_threads(), print_error_msg, print_usage_msg(), and THREAD_NUM_ARG_INDEX.
Referenced by main().
parse_encryption_flag()
static encryption_mode_e parse_encryption_flag (const char * p_encryption_mode_string) static
converts string to mode. Validates string is one of the allowed flags "-e" or "-d".
Parameters
[in] p_encryption_mode_string
Returns
encryption_mode_e success: ENCRYPT_MODE_E,DECRYPT_MODE_E. fail: INVALID_ENCRYPTION_MODE_E = 0xFF.
parse_encryption_key()
static int parse_encryption_key (const char * p_encryption_key_string) static
Extracts encryption key integer from string.
Parameters
[in] p_encryption_key_string
Returns
int
parse_num_of_threads()
static int parse_num_of_threads (const char * p_num_of_threads_string) static
converts string to int. Validates string has only numbers.
Parameters
[in] p_num_of_threads_string
Returns
int success: number of threads, fail: -1
print_usage_msg()
static void print_usage_msg (void) static
print the command line usage for Ceasar program. Call when user entered wrong number of arguments or invalid values.